---
title: "Assignment5"
output: html_document
date: "2023-10-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
library(tidyverse)
library(stats)
library(ggfortify)
library(factoextra)
df_M <- read.csv("Mammal.csv")

mammalSleep <- data.frame(df_M$sleep_total, df_M$sleep_rem)
view(mammalSleep)

a <- mean(df_M$sleep_rem, na.rm=TRUE)
print(a)

mammalSleep <- mammalSleep %>% 
  mutate(df_M.sleep_rem = replace_na(
    df_M.sleep_rem, 1.9)) %>% 
  view()

view(mammalSleep)
mammalSleepS <- scale(mammalSleep)


mammalScaledist <- dist(mammalSleepS)
print(mammalScaledist)

fviz_nbclust(mammalSleepS, kmeans, method="wss")+
  labs(subtitle="Elbow method")

fviz_nbclust(mammalSleepS, kmeans, method="silhouette")+
  labs(subtitle="Silhouette method")




MS1  <- kmeans(mammalSleepS, centers=4, nstart = 5)

autoplot(MS1, mammalSleepS, frame=TRUE)



km2.clusters <- MS1$cluster


rownames(mammalSleepS) <- paste(df_M$name,
                              1:dim(df_M)[1],
                              sep = "_")
fviz_cluster(list(data=mammalSleepS, cluster = km2.clusters))
table(km2.clusters, df_M$name)


```

```{r pressure, echo=FALSE}
plot(pressure)
```

